// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkKstcgSC9BMNXcZAG8F4sg3OrWt1UlK0',
    appId: '1:69532289664:web:240ca4e65ddbe753117465',
    messagingSenderId: '69532289664',
    projectId: 'vehicle-tracker-breno',
    authDomain: 'vehicle-tracker-breno.firebaseapp.com',
    storageBucket: 'vehicle-tracker-breno.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBp_H7VocTAAYcR9gkf65E6sw0FPW18ODQ',
    appId: '1:69532289664:android:e6bd355dd3f1789c117465',
    messagingSenderId: '69532289664',
    projectId: 'vehicle-tracker-breno',
    storageBucket: 'vehicle-tracker-breno.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDrQADrBleLPs5IUlkRYM68DhPwlblGTo',
    appId: '1:69532289664:ios:472990a69da55192117465',
    messagingSenderId: '69532289664',
    projectId: 'vehicle-tracker-breno',
    storageBucket: 'vehicle-tracker-breno.firebasestorage.app',
    iosBundleId: 'com.example.vehicleTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDrQADrBleLPs5IUlkRYM68DhPwlblGTo',
    appId: '1:69532289664:ios:472990a69da55192117465',
    messagingSenderId: '69532289664',
    projectId: 'vehicle-tracker-breno',
    storageBucket: 'vehicle-tracker-breno.firebasestorage.app',
    iosBundleId: 'com.example.vehicleTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkKstcgSC9BMNXcZAG8F4sg3OrWt1UlK0',
    appId: '1:69532289664:web:aa30fb63c95e930f117465',
    messagingSenderId: '69532289664',
    projectId: 'vehicle-tracker-breno',
    authDomain: 'vehicle-tracker-breno.firebaseapp.com',
    storageBucket: 'vehicle-tracker-breno.firebasestorage.app',
  );
}
